src/core/scripts/sample_data.py
hide the stacktrace and only show the most relevant part of it
add a note to the user about the probable cause
fixes SK-CERT/Taranis-NG#3
=> core: sample_data script: exit gracefully on UniqueViolation

docker/README.md
although the column header says "example" and not "default" value, let's
use the value which is actually used
=> docker readme: fix DB_USER value

src/gui/src/components/assess/NewsItemDetail.vue
the source link is already displayed at the top, so remove the link which is displayed below the news item
Before:
(I'm still struggling with docker to get my local changes effective in the docker containers in order to validate that this actually works - any help is appreciated)
=> Assess news items: remove duplicate source link

docker/README.md
With the introduction of Traefik and HTTPS by default, the default port
switched from 8080 to 4443.
Adapting the URLs in the Docker README.
=> Docker readme: Fix URLs/Ports with switch to HTTPS

src/gui/src/store/settings.js
instead of backspace
backspace in browser usually means going to the previous page. Not knowing this shortcut can therefore lead to unintended data loss.
fixes SK-CERT/Taranis-NG#45
=> gui: keyboard shortcuts: use delete for deleting news items

src/gui/src/components/assess/ContentDataAssess.vue
Automatic reloading of news items, when selection mode is active, means
that all selections are lost (=data loss). Disabling automatic reload is
not a perfect solution, items could still be added on the top without
removing existing selections, but this prevents data loss and enhances
the usability significantly.
=> Assess: Do not reload news items when in selection mode

.gitignore
adding more temporary files of editors
change some existing rules to make them more generic, matching all
directory levels
group the entries by type, document that
=> gitignore: add more rules and make others more generic

src/gui/src/assets/keyboard_mixin.js, src/gui/src/components/assess/ToolbarGroupAssess.vue
fixes SK-CERT/Taranis-NG#55
As explained in https://github.com/SK-CERT/Taranis-NG/issues/55#issuecomment-998955319
toolbar lost it's newdial class. I opted to use the class of the news item itself as I was unable find any other suitable existing class assignment and to add a new class to the toolbar. Works fine for me.
And for the multi-select toolbar, the data-btn property was not set because of a human error when rewriting the toolbar
=> fix gui shortcuts in assess

src/gui/src/assets/keyboard_mixin.js
Only Escape is a valid keypress when the search is active
all other presses must be ignored
=> shortcuts: ignore keypresses in search field except Escape

README.md
recommend at least two cpu cores for running TaranisNG
reason: the database container can then easier handle the requests and
other containers do not that easily block database operations
=> doc harware requirements: add cpu cores

README.md, src/gui/README.md
I found that there is a minor mistake in the README, where the URL is referring to port 4433 instead of 4443. There is another reference in the installation manual that does refer to the correct location.
=> Minor change of URL, 4443 instead of 4433

README.md, docker/README.md, docker/docker-compose.yml, docker/prestart_core.sh, src/core/manage.py
This eliminates one step of the installation process: connecting the docker `core` to the docker `collectors` node.
The new node is added by running `manage.py` from within the `core` container.  The new collector will be automatically configured if there are no collectors present. The feature can be disabled by setting the environment variable `SKIP_DEFAULT_COLLECTOR=true`.
=> Automatically initialize "collectors" node on startup

docker/docker-compose.yml
Fix in docker-compose.yml:
**Bots:** TARANIS_NG_CORE_URL variable - bad URL
**DB:** PGTZ variable - problem with timezone error messages in DB after running Bots. I hope there will be no problem for other things :-)
=> Fix DB: PGTZ, Fix Bots: TARANIS_NG_CORE_URL

src/presenters/templates/misp.json
This fixes the generation of template. When some values are missing, the generated JSON file is not valid. This patch might not result in a valid MISP file (it probably is not valid, I haven't checked), but it ensures that the generated file is a valid JSON.
=> fix MISP template

src/gui/src/components/publish/CardProduct.vue, src/gui/src/components/publish/ContentDataPublish.vue
In Products, display "Report type" instead of string "Title" in row detail. Normally Title is repeating on each line and doesn't have any "useful" meaning.
Maybe some settings for that or it's ok? Having on each row some useful information is better than repeating "Title" string.
=> In Products, display "Report type" instead of string "Title" in row detail

src/core/model/news_item.py
When deleting Osint sources is NULL set to in News items (osint_source_id). This cause that function NewsItem.allowed_with_acl() fail and show message `Access denied by ACL`
=> Fix: Access denied by ACL in News items (deleting Osint sources)

.gitignore, src/core/requirements.txt
When trying to build a docker container of core I got into issues related to this sqlalchemy/sqlalchemy/issues/6226. SQLAlchemy version was not specified in requirements.txt, therefore alembic (probably - https://alembic.sqlalchemy.org/en/latest/front.html#dependencies) selected the current version 2.0.7. This created an error in db_migration.py, line 7.  It works as it is supposed to with the latest version of SQLAlchemy 1.4.
=> Specify SQLAlchemy version in requirements.txt for core + .gitignore update

src/core/README.md
the second variable was interpreted as part of the URL
=> minor typo

src/core/managers/publishers_manager.py
BUG introduced with new email publisher. When body or title are not provided by presenter, it behaves as it originally did.
=> fix issue when message title or body are missing

src/gui/src/components/assess/NewsItemAggregateDetail.vue, src/gui/src/components/assess/NewsItemSingleDetail.vue
Saving comments in News Items was not working. Fixed for saving in Single NewsItem and Aggregate NewsItems
=> Fix saving comments in News Items (was not working)

src/gui/src/components/assess/ContentDataAssess.vue
Fixes blinking/jumping in Assess when data are reloaded in various conditions (append on scroll, filter data, change data, click to other category) In future we need return ID changed/deleted records and process only these.
=> Fix blinking/jumping in Assess (data reload)

docker/README.md
Added info about use of compose V2 and deprecation of V1
=> update docker readme with compose V2 info

.gitignore, src/publishers/managers/publishers_manager.py, src/publishers/publishers/__init__.py, src/publishers/publishers/sftp_publisher.py
Separate SFTP (SSH File Transfer Protocol) publisher for transmission of files over SSH and execution of command on remote machine.
- Uses paramiko
- requires only username, url and either password or key  - other is optional
- Works with password or private key - password protected or not
- It is possible to specify path on the remote machine
- After file is uploaded, there is an option to execute command on the remote machine
Also:
- added docstrings
- included some additional files in .gitignore
=> SFTP  publisher

src/bots/managers/log_manager.py, src/collectors/managers/log_manager.py, src/core/managers/log_manager.py, src/presenters/managers/log_manager.py, src/publishers/managers/log_manager.py
Current log function output messages to two different loggers. At beginning is SysLog initialized (default screen) but not used if SYSLOG_URL, SYSLOG_PORT, SYSLOG_ADDRESS are set. Result is that two same messages on the screen.
=> Disable duplicities on the log screen if we have SYSLOG disabled

src/gui/src/components/analyze/NewReportItem.vue
fix: on screen with big records count is dialog centered based on scrollbars range and not on screen size. It is showing outside viewable range and user get "disabled" screen.
Example: Open Assess and press User/Settings -> screen get disabled and nothing shown, but scroll down to see this dialog....
=> fix: dialog is centered based on scrollbars range and not on screen size
