docker/README.md

as discussed with @milankowww, fixes #1

DOC: docker readme: add link to general readme after set-up

---

src/gui/src/components/analyze/ToolbarGroupAnalyze.vue
src/gui/src/components/assess/ToolbarGroupAssess.vue

for better usability
in Assess and Analyze

ToolbarGroup: add title properties explaining function of buttons

---

README.md
ansible/README.md
src/common/taranisng/schema/report_item_type.py
src/core/migrations/alembic.ini
src/core/migrations/versions/03be3f06fca4_typo_occurence_typo.py
src/core/migrations/versions/35855286ef98_.py
src/core/model/report_item_type.py
src/gui/extras/30-envsubst-on-javascript.sh
src/gui/src/components/common/attribute/AttributeBoolean.vue
src/gui/src/components/common/attribute/AttributeCPE.vue
src/gui/src/components/common/attribute/AttributeCVE.vue
src/gui/src/components/common/attribute/AttributeCVSS.vue
src/gui/src/components/common/attribute/AttributeDate.vue
src/gui/src/components/common/attribute/AttributeDateTime.vue
src/gui/src/components/common/attribute/AttributeEnum.vue
src/gui/src/components/common/attribute/AttributeRadio.vue
src/gui/src/components/common/attribute/AttributeRichText.vue
src/gui/src/components/common/attribute/AttributeString.vue
src/gui/src/components/common/attribute/AttributeTLP.vue
src/gui/src/components/common/attribute/AttributeText.vue
src/gui/src/components/common/attribute/AttributeTime.vue
src/gui/src/components/common/attribute/attributes_mixin.js
src/gui/src/components/config/report_types/AttributeTable.vue
src/gui/src/components/config/report_types/NewReportType.vue
src/gui/src/components/layouts/AttributeValueLayout.vue
src/gui/src/i18n/en/messages.js

Apart from typos in the docs there are lots of occurrences of `occurence` in the code. I was only able to check parts of the applications functionality with this change because I'm struggling with #1

fix some typos

---

src/gui/src/components/assess/CardAssess.vue
src/gui/src/components/assess/CardAssessItem.vue
src/gui/src/components/assess/NewsItemDetail.vue
src/gui/src/components/assess/NewsItemSingleDetail.vue

assess: add noreferrer attribute to source links

---

src/bots/remote/core_api.py
src/collectors/collectors/base_collector.py
src/collectors/collectors/slack_collector.py
src/collectors/collectors/web_collector.py
src/core/api/keycloak.py
src/core/auth/keycloak_authenticator.py
src/core/manage.py

using no exception hides other system-exceptions like KeyboardInterrupt,
MemoryError etc.
The most basic exception is just Exception, in lack of knowing better I
chose this one for all occurrences.

fix bare except clauses

---

README.md

for other langauges than english (German, Italian, Spanish)

readme: add alternative source for stop lists

---

README.md
doc/docs/Usage/keyboard.md

as defined in `src/gui/src/store/settings.js`

Document keyboard shortchuts

---

src/collectors/requirements.txt

Forwarding a change proposed by @snyk-bot:
- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
- src/collectors/requirements.txt
Severity                   | Priority Score                    | Issue                   | Upgrade                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------|:-------------------------

Security upgrade lxml from 4.5.0 to 4.6.3

---

src/core/managers/auth_manager.py

create format strings
merge if checks

refactor auth_manager

---

src/publishers/publishers/ftp_publisher.py

allow well formated uris
throw error on wrong scheme

cleanup ftp publisher code

---

src/presenters/run.py
src/publishers/run.py

See https://github.com/gevent/gevent/issues/1016 for details
gevent monkeypatches ssl - if "requests" is used afterwards this leads to unexpected behaviours

monkeypatch before init

---

src/core/migrations/versions/ac311a84207a_added_default_user_accounts.py

static method needed and some default parameters

Fixed migrations in ac311a84207a

---

src/core/model/permission.py
src/core/model/role.py

Fixed crash by editing users (caused by change https://github.com/SK-CERT/Taranis-NG/commit/89c3876dea5965a6b29324962534f4acf0388a5c\)

Fixed crash by editing users

---

src/core/model/asset.py
src/core/model/report_item.py

**Assets** were broken too. Corrected with the same solution used for **role**
in **ReportItemCpe** i delete **report_item** (not used)
in **AssetCpe** som i delete **asset** (not used)
in **AssetVulnerability** i delete **asset** (not used)

Fixed problem with ASSETS (change 89c3876)

---

src/gui/src/components/assess/ToolbarFilterAssess.vue
src/gui/src/i18n/en/messages.js
src/gui/src/views/users/AssessView.vue

Right to the "News items count" display the "Selected news items count"

GUI (Assess): Show number of selected news items

---

src/bots/bots/analyst_bot.py
src/bots/bots/base_bot.py
src/bots/remote/core_api.py
src/core/model/attribute.py

Fixed: Crash on None + missing error code
Better: error log
Simplified regex

Fix: Crash on None,  better Regex

---

src/core/api/publish.py

Fix: bad authentication required for product (PUBLISH_ACCESS, PRODUCT_TYPE_ACCESS)

Fix: bad authentification required for product (PUBLISH_ACCESS)

---

src/core/managers/auth_manager.py

Crash when Signature has expired

Fix: catch error Signature has expired

---

docker/README.md

docker readme: add --pull to docker-compose

---

src/core/auth/test_authenticator.py
src/core/managers/auth_manager.py
src/core/managers/log_manager.py
src/core/requirements.txt

#86 Password data logged in plain text - some property values (password, api_key) are replaced by string CENSORED

#86 Password data logged in plain text

---

src/presenters/templates/pdf_body_template.html
src/presenters/templates/template.html
src/presenters/templates/weekly.html

Fixed: Confidentiality not showing TOP SECRET on PDF, HTML, HTML WEEKLY templates

Fixed: Confidentiality not showing TOP SECRET on reports

---

src/core/migrations/versions/aaf3d8b31972_Numeric_attribute.py
src/gui/src/components/common/attribute/AttributeContainer.vue
src/gui/src/components/common/attribute/AttributeNumber.vue

It was not finished from past. In report items you can now enter only integer numbers in these fields.

Add Attribute number (used in report items)

---

src/presenters/templates/pdf_footer_template.html
src/presenters/templates/template.html
src/presenters/templates/weekly.html

Fixed "random email" in templates

---

src/bots/managers/log_manager.py
src/collectors/collectors/base_collector.py
src/collectors/collectors/rss_collector.py
src/collectors/collectors/web_collector.py
src/collectors/managers/log_manager.py
src/presenters/managers/log_manager.py
src/publishers/managers/log_manager.py

Collectors:
- fix "Popup close" crash
- better logs
- description "Refresh interval in minutes" -> "Refresh interval in minutes (0 to disable)"

Collector enhances (better logs, 0 to disable, popup crash)

---

src/presenters/presenters/misp_presenter.py

Added output for error of misp_presenter the same way as is in other presenters.

misp_presenter templating error output

---

docker/Dockerfile.publishers
src/core/README.md
src/core/auth/ldap_authenticator.py
src/core/managers/auth_manager.py

Fixed bugs from last PR:
- Fixed LDAP crash, moved LDAP_CA_CERT_PATH to env
- Email publisher crash
- updated Readme

Fixed bugs from last PR

---

src/bots/bots/analyst_bot.py
src/bots/bots/base_bot.py
src/bots/managers/log_manager.py
src/core/model/news_item.py

Add: better logs, multiple regex support, possibility disable bot, don't try create duplicity values
Fix: bad condition (missed values with 00 seconds)

Better regex bots

---

src/collectors/collectors/atom_collector.py
src/collectors/collectors/web_collector.py

- Support latest Selenium version (changed methods, depreciated functions, new syntax)
- Added better logs for ATOM collector
Based on PR: #185 Update collectors
!!! NEED THIS PR FIRST TO GET WORKING !!!

Update collectors 2 (Web collector: support for latest Selenium version)

---

src/presenters/presenters/base_presenter.py
src/shared/shared/schema/presenter.py

- adds ID of product from database
- adds date to product
- fixed attribute grouping
- formatting and doc-strings added

Added data to presenter and attribute grouping fix

---

src/gui/src/components/analyze/CardAnalyze.vue
src/gui/src/components/analyze/NewsItemSelector.vue
src/gui/src/components/assess/CardAssess.vue
src/gui/src/components/assess/CardAssessItem.vue
src/gui/src/components/assess/NewsItemAggregateDetail.vue
src/gui/src/components/assess/NewsItemDetail.vue
src/gui/src/components/assess/NewsItemSingleDetail.vue
src/gui/src/components/assess/ToolbarGroupAssess.vue
src/gui/src/components/assets/CardAsset.vue
src/gui/src/components/common/ConfirmDelete.vue
src/gui/src/components/common/card/CardCompact.vue
src/gui/src/components/common/card/CardNode.vue
src/gui/src/components/common/card/CardPreset.vue
src/gui/src/components/config/osint_sources/CardGroup.vue
src/gui/src/components/config/osint_sources/CardSource.vue
src/gui/src/components/config/product_types/CardProductType.vue
src/gui/src/components/config/user/CardUser.vue
src/gui/src/components/publish/CardProduct.vue
src/gui/src/i18n/cs/messages.js
src/gui/src/i18n/en/messages.js
src/gui/src/i18n/sk/messages.js
src/gui/src/store/settings.js

Update based on internal ticket to add delete confirmation window for deleting items.

Delete confirmation window
